spring:
  application:
    name: safebank-api

  datasource:
    url: jdbc:mysql://localhost:3306/safebank?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: admin38123812
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.safebank: DEBUG
    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: false
      logging: slf4j
      log-format: "%(currentTime) | %(executionTime) ms | %(sql)"

# Swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
# Test Profile (테스트 실행 시 자동 적용)
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # H2에서 ID 생성 전략 문제 해결
        id:
          new_generator_mappings: false
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true

logging:
  level:
    com.safebank: WARN
    org.hibernate: WARN