spring:
  application:
    name: safebank-api

  datasource:
    url: jdbc:mysql://localhost:3306/safebank?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: admin38123812
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.safebank: DEBUG
    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: false
      logging: slf4j
      log-format: "%(currentTime) | %(executionTime) ms | %(sql)"

# Swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#
#---
## Test Profile (테스트 실행 시 자동 적용)
#spring:
#  config:
#    activate:
#      on-profile: test
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#
#  sql:
#    init:
#      mode: never
#
#logging:
#  level:
#    com.safebank: WARN